config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users

  resources :users

  resources :events do
    resources :event_attendences, only: [ :create, :destroy ]
    resources :event_invitations, only: [ :create, :destroy ]
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: "User"

  has_many :event_attendences, foreign_key: :attended_event_id, dependent: :destroy
  has_many :attendees, through: :event_attendences, source: :attendee

  has_many :event_invitations, foreign_key: :event_id, dependent: :destroy
  has_many :invitees, through: :event_invitations, source: :invitee
end

app/models/event_attendence.rb
class EventAttendence < ApplicationRecord
  belongs_to :attendee, class_name: "User"
  belongs_to :attended_event, class_name: "Event"
end

app/models/event_invitation.rb
class EventInvitation < ApplicationRecord
  belongs_to :event, class_name: "Event"
  belongs_to :invitee, class_name: "User"

  validates :invitee_id, uniqueness: { scope: :event_id }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :created_events, class_name: "Event", foreign_key: :creator_id, dependent: :destroy

  has_many :event_attendences, foreign_key: :attendee_id, dependent: :destroy
  has_many :attended_events, through: :event_attendences, source: :attended_event

  has_many :event_invitations, foreign_key: :invitee_id, dependent: :destroy
  has_many :invited_events, through: :event_invitations, source: :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  # Changes to the importmap will invalidate the etag for HTML responses
  stale_when_importmap_changes
end

app/controllers/event_attendences_controller.rb
class EventAttendencesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_event

  def create
    is_user_allowed = current_user == @event.creator || @event.invitees.exists?(current_user.id)

    if @event.is_private? && !is_user_allowed
      redirect_to @event, alert: "You have not been invited to this event."
      return
    end

    EventAttendence.find_or_create_by!(
      attendee: current_user,
      attended_event: @event
    )

    redirect_to @event, notice: "You are now attending this event"
  end

  def destroy
    attendence = current_user.event_attendences.find_by!(
      attended_event: @event
    )

    attendence.destroy
    redirect_to @event, notice: "You are no longer attending this event."
  end

  private

  def set_event
    @event = Event.find(params[:event_id])
  end
end

app/controllers/event_invitations_controller.rb
class EventInvitationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_event
  before_action :authorize_creator!

  def create
    @invite = @event.event_invitations.build(event_invitation_params)

    if @invite.save
      redirect_to @event, notice: "User invited"
    else
      redirect_to @event, alert: @invite.errors.full_messages.to_sentence
    end
  end

  private

  def set_event
    @event = Event.find(params[:event_id])
  end

  def authorize_creator!
    redirect_to @event, alert: "Not authorized" unless @event.creator == current_user
  end

  def event_invitation_params
    params.require(:event_invitation).permit(:invitee_id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])

    return if !(@event.is_private?)

    allowed =
      @event.creator == current_user ||
      @event.invitees.include?(current_user) ||
      @event.attendees.include?(current_user)

    redirect_to events_path, alert: "This event is private." unless allowed
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.created_events.build(event_params)

    if @event.save
      redirect_to @event, notice: "Event created successfully."
    else
      render :new, alert: "Failed to create event."
    end
  end

  private

  def event_params
    params.expect(event: [ :title, :location, :date, :is_private ])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = current_user
    @created_events = @user.created_events
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_attendences_helper.rb
module EventAttendencesHelper
end

app/helpers/event_invitations_helper.rb
module EventInvitationsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<h1>All Events</h1>

<ul>
  <% @events.each do |event| %>
    <% if event.is_private %>
      <% if event.invitees.include?(current_user) || event.creator == current_user %>
        <li><%= link_to event.title, event_path(event) %>🔓</li>
      <% else %>
        <li><%= link_to event.title, event_path(event) %>🔒</li>
      <% end %>
    <% else %>
      <li><%= link_to event.title, event_path(event) %>📢</li>
    <% end %>  
  <% end %>
</ul>

app/views/events/new.html.erb
<%= form_with model: @event do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% @event.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :location %><br>
    <%= form.text_area :location %>
    <% @event.errors.full_messages_for(:location).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :date %><br>
    <%= form.date_field :date %>
    <% @event.errors.full_messages_for(:date).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.check_box :is_private %>
    <%= form.label :is_private, "Make this event private" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/events/show.html.erb
<h1><%= @event.title %></h1>
<p>Location: <%= @event.location %></p>
<p>Date: <%= @event.date %></p>
<p>Privacy: <%= @event.is_private ? "This is a private event" : "This isn't a private event" %></p>


<!-- Invite feature only available when event is private -->
<% if @event.is_private? && @event.creator == current_user %>
  <h3>Invite a user</h3>

  <%= form_with model: [@event, EventInvitation.new] do |form| %>
    <%= form.collection_select :invitee_id,
      User.where.not(id: current_user.id),
      :id,
      :email,
      prompt: "Select a user"
    %>
    <%= form.submit "Invite" %>
  <% end %>
<% end %>

<% attendence = current_user.event_attendences.find_by(attended_event_id: @event) %>
<% if attendence %>
  <%= button_to "Unattend Event", 
      event_event_attendence_path(@event, attendence), 
      method: :delete 
  %>
<% else %>
  <%= button_to "Attend Event", 
      event_event_attendences_path(@event), 
      method: :post 
  %>
<% end %>

<h3>Event Attendees</h3>
<ul>
  <% @event.attendees.each do |attendee| %>
  <li><%= attendee.email %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Odin Private Events" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Odin Private Events">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <% if user_signed_in? %>
      <%= current_user.email %>
      <nav style="display: flex; justify-content: space-between;">
        <div>
          <ul style="display: flex; flex-direction: column;">
            <li><%= link_to "All Events", events_path %></li>
            <li><%= link_to "My Events", user_path(current_user) %></li>
            <li><%= link_to "Create New Event", new_event_path %></li>
          </ul>
        </div>
        
        <div>
          <% if user_signed_in? %>
            <%= link_to"Sign out", destroy_user_session_path, data: { turbo_method: :delete } %>
          <% else %>
            <%= link_to "Sign In", new_user_session_path %>
          <% end %>
        </div>
      </nav>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<h1>My Created Events</h1>

<ul>
  <% @created_events.each do |event| %>
    <% if event.is_private %>
      <% if event.invitees.include?(current_user) || event.creator == current_user %>
        <li><%= link_to event.title, event_path(event) %>🔓</li>
      <% else %>
        <li><%= link_to event.title, event_path(event) %>🔒</li>
      <% end %>
    <% else %>
      <li><%= link_to event.title, event_path(event) %>📢</li>
    <% end %>
  <% end %>
</ul>